-- SCHEMA

-- FIRST WE CREATE THE DATABASE
CREATE DATABASE burgers_db;

-- NOW WE SELECT THE DATABASE TO USE IT
USE burgers_db;

-- NOW WE CAN CREATE A TABLE INSIDE THE DATABASE ABOVE
CREATE TABLE burgers
(
	id INTEGER NOT NULL AUTO_INCREMENT,
	burger_name VARCHAR(255) NOT NULL,
	devoured BOOLEAN DEFAULT false,
	date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

-- THIS LINE HELPS US SELECT THE TABLE ABOVE AND ACTUALLY SEE IT IN MySQLWorkbench
SELECT * FROM burgers;


